"""added renewal_no

Revision ID: 77718e38ba91
Revises: fbe59a745def
Create Date: 2026-05-28 10:29:59.994150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77718e38ba91'
down_revision = 'fbe59a745def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renewal_no', sa.String(length=50), nullable=True))
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('renewal_no')

    # ### end Alembic commands ###
