"""add invoice_no column

Revision ID: 954ff0e970d6
Revises: 77718e38ba91
Create Date: 2026-05-28 20:40:59.409272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954ff0e970d6'
down_revision = '77718e38ba91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_no', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(
            "uq_invoices_invoice_no",
            ['invoice_no']
        )

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('invoice_no')

    # ### end Alembic commands ###
