"""add date_paid index

Revision ID: c7630f62ea3d
Revises: 3c8e0c661767
Create Date: 2026-06-03 12:31:09.303037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7630f62ea3d'
down_revision = '3c8e0c661767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_date_paid'), ['date_paid'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_date_paid'))

    # ### end Alembic commands ###
